# Publish events from SNS to PagerDuty
service: aws-sns-to-pagerduty-event

plugins:
  - serverless-parameters


custom:
  stage: "${opt:stage, env:SLS_STAGE, 'dev'}"
  log_level: "${env:LOG_LEVEL, 'INFO'}"

  parameters:
    PagerDutySnsSubscriberEndpoint:
      Type: String
      Description: "PagerDuty Integration SNS Subscription endpoint"
      Default: "${env:SNS_ENDPOINT, ''}"

provider:
  name: aws
  stage: ${self:custom.stage}
  runtime: python3.6
  environment:
    LOG_LEVEL: ${self:custom.log_level}
  stackTags:
    x-service: ${self:service}
    x-stack: ${self:service}-${self:provider.stage}


resources:
  Resources:
    PagerDutyEventPublishTopic:
      Type: "AWS::SNS::Topic"

    PagerDutyEventPublishSubscription:
      Type: "AWS::SNS::Subscription"
      Properties:
        TopicArn:
          Ref: PagerDutyEventPublishTopic
        Protocol: https
        Endpoint:
          Ref: PagerDutySnsSubscriberEndpoint

    PagerDutyEventPublishTopicArnSsmParam:
      Type: AWS::SSM::Parameter
      Properties:
        # NOTE: SSM names can't start with AWS as our service name does.
        Name: "/sns-to-pagerduty-event/${self:provider.stage}/PagerDutyEventPublishTopicArn"
        Description: "ARN of SNS topic for publishing events to PagerDuty."
        Type: String
        Value:
          Ref: PagerDutyEventPublishTopic

  Outputs:
    PagerDutyEventPublishTopicArnSsmParam:
      Description: "Name of SSM parameter with SNS Topic ARN."
      Value:
        Ref: PagerDutyEventPublishTopicArnSsmParam
      Export:
        Name: ${self:service}-${self:custom.stage}-PagerDutyEventPublishTopicArnSsmParam

